# Loco configuration file documentation

# Application logging configuration
logger:
  # Enable or disable logging.
  enable: true
  # Enable pretty backtrace (sets RUST_BACKTRACE=1)
  pretty_backtrace: true
  # Log level, options: trace, debug, info, warn or error.
  level: debug
  # Define the logging format. options: compact, pretty or json
  format: compact
  # By default the logger has filtering only logs that came from your code or logs that came from `loco` framework. to see all third party libraries
  # Uncomment the line below to override to see all third party libraries you can enable this config and override the logger filters.
  # override_filter: trace

# Web server configuration
server:
  # Port on which the server will listen. the server binding is 0.0.0.0:{PORT}
  port: 5150
  # Binding for the server (which interface to bind to)
  binding: localhost
  # The UI hostname or IP address that mailers will point to.
  host: http://localhost
  # Out of the box middleware configuration. to disable middleware you can changed the `enable` field to `false` of comment the middleware block
  middlewares:
    limit_payload:
      enable: true
      body_limit: 64kb
    secure_headers:
      enable: true
      preset: empty
      overrides:
        Content-Security-Policy: "default-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; object-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'"
        Referrer-Policy: same-origin
        X-Content-Type-Options: nosniff
        X-Frame-Options: DENY
        Permissions-Policy: "camera=(), microphone=(), geolocation=()"
    static:
      enable: true
      must_exist: false
      folder:
        uri: /static
        path: assets/static

# Application-specific settings. Values are required from the process environment.
settings:
  business:
    default_currency: EUR
    default_collection_limit: 25
    maximum_collection_limit: 200
  surrealdb:
    endpoint: '{{ get_env(name="SURREALDB_ENDPOINT") }}'
    username: '{{ get_env(name="SURREALDB_ROOT_USERNAME") }}'
    password: '{{ get_env(name="SURREALDB_ROOT_PASSWORD") }}'
    namespace: '{{ get_env(name="SURREALDB_NAMESPACE") }}'
    database: '{{ get_env(name="SURREALDB_DATABASE") }}'
    connection_timeout_ms: 5000
    engine: websocket
